//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeThi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamID { get; set; }
        public string ExamName { get; set; }
        public string Image { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID { get; set; }
        public string Author { get; set; }
        public string UrlFile { get; set; }
        public string Keyword { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> DownloadCount { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Users Users { get; set; }
    }
}
